question_data = [
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "Linux was first created as an alternative to Windows XP.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Film",
     "question": "Which animated movie was first to feature a celebrity as a voice actor?",
     "correct_answer": "Aladdin",
     "incorrect_answers": ["Toy Story", "James and the Giant Peach",
                           "The Hunchback of Notre Dame"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "Which Pok&eacute;mon and it&#039;s evolutions were banned from appearing in a main role after the Episode 38 Incident?",
     "correct_answer": "The Porygon Line",
     "incorrect_answers": ["The Pikachu Line", "The Elekid Line", "The Magby Line"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Film",
     "question": "What is the name of the character Nicolas Cage plays in the movie &quot;National Treasure?&quot;",
     "correct_answer": "Benjamin Franklin Gates",
     "incorrect_answers": ["Thomas Jefferson Walker", "George Washington Swanson", "John Quincy Beckett"]},
    {"type": "multiple", "difficulty": "easy", "category": "Geography",
     "question": "How many countries does Mexico border?", "correct_answer": "3", "incorrect_answers": ["2", "4", "1"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Books",
     "question": "What was the last message of the Dolphins in &quot;The Hitchhiker&#039;s Guide to the Galaxy&quot;?",
     "correct_answer": "&quot;So long, and thanks for all the fish.&quot;",
     "incorrect_answers": ["&quot;The answer is 42.&quot;", "&quot;Land of the brave.&quot;",
                           "&quot;Goodbye cruel world!&quot;"]},
    {"type": "multiple", "difficulty": "hard", "category": "History", "question": "Which day did World War I begin?",
     "correct_answer": "July 28", "incorrect_answers": ["January 28", "June 28", "April 28"]},
    {"type": "multiple", "difficulty": "easy", "category": "Vehicles",
     "question": "Which of the following collision avoidance systems helps airplanes avoid colliding with each other?",
     "correct_answer": "TCAS", "incorrect_answers": ["GPWS", "OCAS", "TAWS"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Television",
     "question": "In &quot;Doctor Who&quot;, the Doctor gets his TARDIS by stealing it.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Musicals &amp; Theatres",
     "question": "The World Chess Championship in Chess, Act 1 is set in which Italian city?",
     "correct_answer": "Merano", "incorrect_answers": ["Venice", "Milan", "Rome"]},
    {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
     "question": "Unturned originally started as a Roblox game.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "medium", "category": "Geography",
                                       "question": "Israel is 7 hours ahead of New York.", "correct_answer": "True",
                                       "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Television",
     "question": "Which actor was not a major character in TV Show Freaks and Geeks?", "correct_answer": "Jonah Hill",
     "incorrect_answers": ["Jason Segel", "Seth Rogen", "James Franco"]},
    {"type": "multiple", "difficulty": "hard", "category": "History",
     "question": "Bohdan Khmelnytsky was which of the following?", "correct_answer": "Leader of the Ukrainian Cossacks",
     "incorrect_answers": ["General Secretary of the Communist Party of the USSR", "Prince of Wallachia",
                           "Grand Prince of Novgorod"]},
    {"type": "multiple", "difficulty": "medium", "category": "History",
     "question": "The fraudelent doctor John R. Brinkley acummulated great fame and wealth in the early 1900s offering what service?",
     "correct_answer": "Goat testicles transplant",
     "incorrect_answers": ["Pig blood transfusion", "Cow liver transplant", "Turkey breast implants"]},
    {"type": "multiple", "difficulty": "medium", "category": "History",
     "question": "The creator of the Enigma Cypher and Machine was of what nationality?", "correct_answer": "German",
     "incorrect_answers": ["American", "British", "Polish"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "In which order do you need to hit some Deku Scrubs to open the first boss door in &quot;Ocarina of Time&quot;?",
     "correct_answer": "2, 3, 1", "incorrect_answers": ["1, 2, 3", "1, 3, 2", "2, 1, 3"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Music",
     "question": "Which band released songs suchs as &quot;Rio&quot;, &quot;Girls on Film&quot;, and &quot;The Reflex&quot;?",
     "correct_answer": "Duran Duran", "incorrect_answers": ["The Cure", "New Order", "Depeche Mode"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
     "question": "Kublai Khan is the grandchild of Genghis Khan?", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Japanese Anime &amp; Manga",
     "question": "Krusty is the guild master of which guild in &quot;Log Horizon&quot;?", "correct_answer": "D. D. D",
     "incorrect_answers": ["Silver Sword", "West Wind Brigade", "Oceanic Systems (Marine Agency)"]}]
